#!/bin/sh

# Get the codename of the Ubuntu release for sources that require it.
VERSION=`lsb_release -c | cut -f2`

sudo apt update

# ******************************************************************************
# Remove Junk
# ******************************************************************************
sudo apt purge -y \
	abiword \
	aisleriot \
	brasero \
	catfish \
	cheese \
	firefox \
	five-or-more \
	four-in-a-row \
	gconf2 \
	gnome-clocks \
	gnome-dictionary \
	gnome-mahjongg \
	gnome-mines \
	gnome-mpv \
	gnome-nibbles \
	gnome-robots \
	gnome-sound-recorder \
	gnome-sudoku \
	gnumeric \
	guvcview \
	hexchat \
	hitori \
	iagno \
	inkscape \
	libreoffice \
	lightsoff \
	mtpaint \
	mpv \
	onboard \
	onboard-data \
	parole \
	pidgin \
	pidgin-data \
	pidgin-otr \
	pidgin-libnotify \
	qgis \
	sgt-puzzles \
	simple-scan \
	swell-foop \
	sylpheed \
	tali \
	totem \
	thunderbird \
	ubuntu-mate-welcome \
	vlc \
	xfburn \
	xfce4-dict \
	xfce4-notes \
	xul-ext-ubufox

# ******************************************************************************
# Add Repos
# ******************************************************************************

# Some prereqs
sudo apt install -y apt-transport-https ca-certificates curl software-properties-common

# sublime-text
wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list

# Docker
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $VERSION stable"

sudo apt update

# ******************************************************************************
# install packages
# ******************************************************************************

# install separately so failures don't cascade
sudo apt install -y docker-ce
sudo apt install -y docker-compose
# sudo apt install -y evolution
# sudo apt install -y evolution-ews
sudo apt install -y git
sudo apt install -y htop
sudo apt install -y openssh-server
sudo apt install -y openssh-sftp-server
sudo apt install -y openvpn
sudo apt install -y plank
sudo apt install -y python-pip
sudo apt install -y python-future
sudo apt install -y python3
sudo apt install -y python3-future
sudo apt install -y snapd
sudo apt install -y sublime-text
sudo apt install -y tmux
sudo apt install -y transmission
sudo apt install -y xfce4-appmenu-plugin
sudo apt install -y vim
sudo apt install -y zsh

sudo apt autoremove

# ******************************************************************************
# Snaps
# ******************************************************************************

sudo snap install canonical-livepatch
sudo snap install chromium
sudo snap install firefox
sudo snap install hiri
sudo snap install --classic slack
sudo snap install spotify
sudo snap install termius-app
sudo snap install vlc
sudo snap install --classic vscode

# ******************************************************************************
# Other
# ******************************************************************************

# Finish Docker Setup
sudo usermod -aG docker $(whoami)

# Set zsh as default shell
sudo usermod -s /usr/bin/zsh $(whoami)

# rust
curl https://sh.rustup.rs -sSf | sh

# Get 1Password
curl -fsSL https://cache.agilebits.com/dist/1P/op/pkg/v0.8.0/op_linux_arm_v0.8.0.zip -o ./op_linux.zip
unzip op_linux_arm_v0.8.0.zip
gpg --receive-keys 3FEF9748469ADBE15DA7CA80AC2D62742012EA22
gpg --verify op.sig op
mv op_linux_arm_v0.8.0/op $HOME/bin/
op update

# Enable Livepatch
sudo canonical-livepatch enable <token>

cd script
./bootstrap

# Set zsh as default shell
sudo usermod -s /usr/bin/zsh $(whoami)
