#!/bin/sh

# Get the codename of the Ubuntu release for sources that require it.
VERSION=`lsb_release -c | cut -f2`

sudo apt update

# ******************************************************************************
# Remove Junk
# ******************************************************************************
sudo apt purge -y \
	abiword \
	aisleriot \
	brasero \
	catfish \
	cheese \
	firefox \
	five-or-more \
	four-in-a-row \
	gconf2 \
	gnome-clocks \
	gnome-dictionary \
	gnome-mahjongg \
	gnome-mines \
	gnome-mpv \
	gnome-nibbles \
	gnome-robots \
	gnome-sound-recorder \
	gnome-sudoku \
	gnumeric \
	guvcview \
	hexchat \
	hitori \
	iagno \
	inkscape \
	libreoffice \
	lightsoff \
	mtpaint \
	mpv \
	onboard \
	onboard-data \
	parole \
	pidgin \
	pidgin-data \
	pidgin-otr \
	pidgin-libnotify \
	qgis \
	sgt-puzzles \
	simple-scan \
	swell-foop \
	sylpheed \
	tali \
	totem \
	thunderbird \
	ubuntu-mate-welcome \
	vlc \
	xfburn \
	xfce4-dict \
	xfce4-notes \
	xul-ext-ubufox

# ******************************************************************************
# Add Repos
# ******************************************************************************

# Some prereqs
sudo apt install -y apt-transport-https ca-certificates curl software-properties-common gnupg

# Sublime Text (sublime-text)
wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list

# Docker (docker-ce, docker-compose)
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $VERSION stable"

# Google Cloud (google-cloud-sdk)
curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list

# QGIS
wget -qO - https://qgis.org/downloads/qgis-2019.gpg.key | sudo apt-key add -
echo "deb [arch=amd64] https://qgis.org/ubuntu/ $VERSION main" | sudo tee -a /etc/apt/sources.list

sudo apt update

# ******************************************************************************
# install packages
# ******************************************************************************

# install separately so failures don't cascade
sudo apt install -y docker-ce
sudo apt install -y docker-compose
# sudo apt install -y evolution
# sudo apt install -y evolution-ews
sudo apt install -y git
sudo apt install -y google-cloud-sdk
sudo apt install -y htop
sudo apt install -y openssh-server
sudo apt install -y openssh-sftp-server
sudo apt install -y openvpn
sudo apt install -y plank
sudo apt install -y python-pip
sudo apt install -y python-future
sudo apt install -y python3
sudo apt install -y python3-future
sudo apt install -y snapd
sudo apt install -y sublime-text
sudo apt install -y tmux
sudo apt install -y transmission
sudo apt install -y xfce4-appmenu-plugin
sudo apt install -y vim
sudo apt install -y zsh

sudo apt autoremove

# ******************************************************************************
# Snaps
# ******************************************************************************

sudo snap install canonical-livepatch
sudo snap install firefox
sudo snap install hiri
sudo snap install libreoffice
sudo snap install --classic slack
sudo snap install spotify

# ******************************************************************************
# Other
# ******************************************************************************

# Finish Docker Setup
sudo usermod -aG docker $(whoami)

# Set zsh as default shell
sudo usermod -s /usr/bin/zsh $(whoami)

# rust
curl https://sh.rustup.rs -sSf | sh

# Enable Livepatch
# sudo canonical-livepatch enable <token>

cd script
./bootstrap

# Set zsh as default shell
sudo usermod -s /usr/bin/zsh $(whoami)
