---
version: '2'
services:
  db:
    image: mariadb
    hostname: db
    container_name: db
    restart: always
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    # networks:
    #   - thingvellir
    environment:
      - MYSQL_DATABASE=maria
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=jacob
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  nextcloud:
    image: nextcloud
    hostname: nextcloud
    restart: always
    env_file: .env
    ports:
      - 8080:80
    depends_on:
       - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=maria
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - MYSQL_USER=jacob
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - data:/var/www/html/data
      - config:/var/www/html/config
      - apps:/var/www/html/apps
  wordpress:
    image: wordpress:latest
    hostname: wordpress
    container_name: wordpress
    depends_on:
       - db
    ports:
       - "9000:80"
    restart: always
    environment:
      WORDPRESS_DB_NAME: maria
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: jacob
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
  calibre:
    image: regueiro/calibre-server
    hostname: calibre
    container_name: calibre
    restart: always
    volumes:
      - calibre:/opt/calibre/library
    ports:
      - "9001:8000" 
volumes:
  data:
  config:
  apps:
  mariadb:
  wordpress:
  calibre:
