---
version: '2'
services:
  nginx:
    image: nginx
    hostname: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "./certs:/etc/nginx/certs:ro"
    environment:
      - DEFAULT_HOST=jacobpledger.com
      - VIRTUAL_PROTO=https
      - VIRTUAL_PORT=443
  nginx-gen:
    image: jwilder/docker-gen
    hostname: nginx-gen
    container_name: nginx-gen
    volumes:
      - "./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    volumes_from:
      - "nginx"
  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./certs:/etc/nginx/certs:rw"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
    volumes_from:
      - "nginx-gen"
    environment:
      - NGINX_PROXY_CONTAINER=nginx
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
      - VIRTUAL_HOST=jacobpledger.com,www.jacobpledger.com
      - LETSENCRYPT_HOST=jacobpledger.com,www.jacobpledger.com
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
  db:
    image: mariadb
    hostname: db
    container_name: db
    restart: always
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=maria
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=jacob
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  nextcloud:
    image: nextcloud
    hostname: nextcloud
    restart: always
    env_file: .env
    ports:
      - 8080:80
    depends_on:
       - db
    environment:
      - VIRTUAL_HOST=nextcloud.jacobpledger.com
      - LETSENCRYPT_HOST=jacobpledger.com, www.jacobpledger.com
      # - LETSENCRYPT_TEST=true
      - MYSQL_HOST=db
      - MYSQL_DATABASE=maria
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - MYSQL_USER=jacob
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - data:/var/www/html/data
      - config:/var/www/html/config
      - apps:/var/www/html/apps
  ghost:
    image: ghost:alpine
    hostname: ghost
    container_name: ghost
    restart: always
    ports:
      - "9080:2368"
    environment:
      - database__client=sqlite3
      - database__connection__host=db
      - database__connection__user=jacob
      - database__connection__password=${MYSQL_PASSWORD}
      - database__connection__database=maria
      - VIRTUAL_HOST=jacobpledger.com,www.jacobpledger.com
      - LETSENCRYPT_HOST=jacobpledger.com,www.jacobpledger.com
      # - LETSENCRYPT_TEST=true
  calibre:
    image: regueiro/calibre-server
    hostname: calibre
    container_name: calibre
    restart: always
    volumes:
      - calibre:/opt/calibre/library
    ports:
      - "9001:8000"
    environment:
      - VIRTUAL_HOST=books.jacobpledger.com
      - LETSENCRYPT_HOST=books.jacobpledger.com
      # - LETSENCRYPT_TEST=true
volumes:
  data:
  config:
  apps:
  mariadb:
  calibre:
