---
version: '3'
services:
   db:
     image: mysql:5.7
     hostname: db
     container_name: db
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
   wordpress:
     image: wordpress:latest
     hostname: wordpress
     container_name: wordpress
     depends_on:
       - db
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
  calibre:
    image: calibre
    hostname: calibre
    container_name: calibre
    build:
      context: .
      dockerfile: ./docker/calibre/Dockerfile
    networks:
      - jotunheim
    restart: always
    volumes:
      - .:/home/calibre/
    ports:
      - "8000:8000"
volumes:
    db_data:
