---
version: '3'
services:
  db:
    image: mysql:5.7
    hostname: db
    container_name: db
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  wordpress:
    image: wordpress:latest
    hostname: wordpress
    container_name: wordpress
    depends_on:
       - db
    ports:
       - "8000:80"
    restart: always
    volumes:
      - ./data/wordpress/:.
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
  calibre:
    image: calibre
    hostname: calibre
    container_name: calibre
    build:
      context: .
      dockerfile: ./docker/calibre/Dockerfile
    restart: always
    volumes:
      - ./data/calibre/:.
    ports:
      - "8000:8000" 
  nextcloud:
    image: nextcloud
    restart: always
    volumes:
      - ./data/nextcloud/:/var/www/html/
