
# Configuration file for fe-qgis-plugin
# YAML format (key: value)
#
# Define username and geoserver URLs to use
#
# ex.
#   username: someguy
#   imagery-geoserver-url: https://some-url.org/geoserver
#
# Please do not end the URL with /
# A backup of the original form of this file can be found as config.yaml.bak

username: farmcommand
imagery-geoserver-url: https://imagery-bse-stageb.granduke.net/geoserver
canplug-geoserver-url: https://bse-qa.granduke.net/geoserver
field-geoserver-url: https://geoserver-imagery.granduke.net/geoserver
developer-options: true
wcs-tile-size: 1024
