#!/bin/sh

# ******************************************************************************
# Install packages from the default repos.
# ******************************************************************************

# install separately so failures don't cascade
sudo apt install -y bluebird-gtk-theme
sudo apt install -y emacs
sudo apt install -y evolution  # Email client
sudo apt install -y evolution-ews  # For MS Exchange
sudo apt install -y font-manager
sudo apt install -y fonts-firacode
sudo apt install -y git
sudo apt install -y htop
sudo apt install -y ncdu  # NCurses Disk Usage
sudo apt install -y ntp  # network time sync
sudo apt install -y openssh-server
sudo apt install -y openssh-sftp-server
sudo apt install -y python-pip
sudo apt install -y python3
sudo apt install -y snapd
sudo apt install -y tmux  # Terminal multiplexer
sudo apt install -y transmission  # Torrent client
sudo apt install -y xfce4-appmenu-plugin  # Menu bar in panel
sudo apt install -y vim  # Command-line editing
sudo apt install -y webcamoid  # Webcam tool
sudo apt install -y wavemon  # Wifi monitoring tool