#!/bin/sh

# *****************************************************************************
# Install Snaps
# *****************************************************************************

sudo snap install bitwarden 
sudo snap install --classic code
sudo snap install firefox
sudo snap install --classic slack
ln -s /snap/slack/latest/usr/share/pixmaps/slack.png  /usr/share/pixmaps/slack.png  # fix missing Slack icon
sudo snap install spotify