#!/bin/sh

# ******************************************************************************
# Install packages from the default repos.
# ******************************************************************************

# install separately so failures don't cascade
sudo apt install -y audacity
sudo apt install -y flatpak
sudo apt install -y fonts-firacode
sudo apt install -y git
sudo apt install -y google-cloud-sdk
sudo apt install -y htop
sudo apt install -y ntp  # network time sync
sudo apt install -y openssh-server
sudo apt install -y openssh-sftp-server
sudo apt install -y python-pip
sudo apt install -y python3
sudo apt install -y snapd
sudo apt install -y tmux
sudo apt install -y transmission
sudo apt install -y xfce4-appmenu-plugin
sudo apt install -y vim