;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	beginning-of-buffer
	buffer-menu
	dap-tooltip-mouse-motion
	end-of-buffer
	ignore
	kill-region
	move-line-down
	move-line-up
	py-electric-colon
	py-electric-delete
	py-indent-or-complete
	yank-rectangle
	))

(setq mc/cmds-to-run-once
      '(
	customize-browse
	))
